### ISSUE TITLE
How to perform forecasting on a data for which we only have the index?

### ISSUE THREAD

**Issue by emanhamed** [welch/seasonal#11]
What if I have only the time index of the data and I want to forecast the y value. I see that your model depends on the ground truth y values to update the state for the next forecasting. Is it possible to do forecasting without having the y ?

**Comment by welch** [comment]
Have a look at `examples/hw.py`. The `forecast()` function lets your run a Holt-Winters model forward without additional observations. Coupla things here:

1. the `seasonal` package is not a H-W implementation, though it uses the same representation for seasonality. `hw.py` shows how one might generally use `seasonal` when writing a forecaster, we just chose H-W for the example because it is so simple to code.

2. H-W forecasts are rather dull -- they simply play back the most recent observation (this is the most-likely next observation), offset by current trend and seasonal estimates.
