### ISSUE TITLE
Already installed matplotlib, but 'Error: matplotlib must be installed to use the --plot option'

### ISSUE THREAD

**Issue by forhonourlx** [welch/seasonal#6]
Hi Welch

I am interested in your nice work, but I got a little problem.
When I try to plot, it shows 'Error: matplotlib must be installed to use the --plot option'
But 'Successfully installed cycler-0.10.0 matplotlib-1.5.3 numpy-1.11.2 pyparsing-2.1.9 python-dateutil-2.5.3 pytz-2016.7 six-1.10.0'

Do you know the possible reason?

Thanks & Regards,

Simon

**Comment by welch** [comment]
That error happens when matplot.pyplot cannot be imported.
if you start up python, and type `from matplotlib import pyplot`,
does it succeed, and is `pyplot` non-null? I don't know what
would cause the fail, but strongly recommend using the anaconda
python distribution as a way to have this and the numpy/scipy 
ecosystem pre-installed without pain.
